name: Auto Publish Website # 自动部署的名称
on:
  push:
    branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境，告诉它运行在什么环境
    steps: # 步骤

    # 第一步：下载源码（CI/CD拉取代码到自己的本地）
    - name: Checkout
      uses: actions/checkout@main

    # 第五步：部署到服务器
    - name: Deploy
      uses: appleboy/ssh-action@master # 使用ssh链接服务器
      with:
        host: ${{ secrets.HOST }} #配置的服务器地址
        username: ${{ secrets.USERNAME }} #配置的服务器用户名
        password: ${{ secrets.PASSWORD }} #配置的密码
        port: ${{ secrets.PORT }} #配置的端口
        script: | # 执行命令（运行到服务器）cd：要确保服务器有这个目录； wget：下载上一步的release到服务器； tar：解压； 安装依赖；启动服务
          cd /home/gitaction
          echo 1111
#          git clone git@github.com:mengfengkong/test-for-git.git
